# Generated by Django 2.2 on 2019-06-07 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(default='N/A', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gamename', models.CharField(default='N/A', max_length=100)),
                ('maxPlayer', models.PositiveSmallIntegerField(default=2, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steamid', models.CharField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('ranking', models.CharField(max_length=20)),
                ('signUpDate', models.DateField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=100, null=True)),
                ('introduction', models.TextField(blank=True)),
                ('running', models.BooleanField(default=False)),
                ('chatroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Chatroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.PositiveSmallIntegerField(default=5, max_length=10)),
                ('matchDate', models.DateField(default=django.utils.timezone.now)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game')),
                ('rateeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0.0, max_length=10.0)),
                ('recentUpdate', models.DateField(default=django.utils.timezone.now)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game')),
                ('playerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='MatchedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatroom', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GameSeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gamename', models.TextField(default='gamename')),
                ('users', models.ManyToManyField(null=True, related_name='seeds', to='match.Profile')),
            ],
        ),
    ]
