# Generated by Django 2.2 on 2019-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameseed',
            name='imgfile',
            field=models.TextField(null=True),
        ),
    ]
