# Generated by Django 2.2 on 2019-06-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20190607_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='steamid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
