# Generated by Django 2.2 on 2019-04-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20190420_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='playerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
    ]
