# Generated by Django 2.2 on 2019-04-19 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20190420_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.PositiveSmallIntegerField(default=5, max_length=10)),
                ('matchDate', models.DateField(default=django.utils.timezone.now)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game')),
                ('rateeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile')),
            ],
        ),
    ]
