# Generated by Django 2.2 on 2019-05-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20190524_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='raterId',
        ),
        migrations.AddField(
            model_name='review',
            name='rateeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
    ]
