# Generated by Django 2.2 on 2019-06-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20190606_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
        migrations.CreateModel(
            name='GameSeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gamename', models.TextField(default='gamename')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile')),
            ],
        ),
    ]
