# Generated by Django 2.2 on 2019-05-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20190524_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(default='N/A', max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
    ]
