# Generated by Django 2.2 on 2019-06-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20190606_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameseed',
            name='user',
        ),
        migrations.AddField(
            model_name='gameseed',
            name='users',
            field=models.ManyToManyField(null=True, related_name='seeds', to='match.Profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Game'),
        ),
    ]
